version: '3.9'

services:
  database:
    image: 'postgres:17-alpine'
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    networks:
      - enemhub-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env.development
    depends_on:
      database:
        condition: service_healthy
    networks:
      - enemhub-network

networks:
  enemhub-network:
    driver: bridge